### ISSUE TITLE
tooltip issue when displaying how much % an enemy is worth

### ISSUE THREAD

**Issue by Apoxiosis** [Stinth/GottaGoFaster#1]
![image](https://user-images.githubusercontent.com/43189648/208314176-8d52acd0-c16d-4722-8f60-f0224b738d2a.png)

**Comment by Apoxiosis** [comment]
no idea what causes this, sometimes it displays correctly, sometimes it only displays 2-3 instances of the %, other times it absolutely blasts my screen

**Comment by Stinth** [comment]
Thank you for the report. It should be fixed with commit #[43bc348](https://github.com/Stinth/GottaGoFaster/commit/43bc348a89b9a2c9e1810ef69a76762ed10daa2f) and added to the addon in latest version [v1.2.5](https://github.com/Stinth/GottaGoFaster/tree/v1.2.5) .
