### ISSUE TITLE
Inaccurately tracks overall deaths and timers

### ISSUE THREAD

**Issue by ry-java** [Stinth/GottaGoFaster#11]
![Wow_zQI8MGtbPn](https://github.com/user-attachments/assets/be1dc5d4-6351-4f9a-8e06-0b78da164cfe)
![firefox_xbtJNeqxW5](https://github.com/user-attachments/assets/c1cd2621-87e4-4184-aeb0-75872f51a8d6)

After a random amount of time/deaths there because a discrepancy between the timer and death counting.
Don't believe it's entirely related to #10 as the issue was present before hand.

Will look into it a bit more and hopefully find a fix but its hard to find where exactly the issue occurs without a ptr/depleting 7s on purpose

**Comment by Stinth** [comment]
Thank you for the issue. My gut feeling is it stops counting deaths after you deplete the key, but I have not looked into it

**Comment by ry-java** [comment]
It definitely stops after a deplete but before the depletion my friend had 23 deaths on the timer and I still had a minute left on the timer and only 20. (Maybe the group deaths pushed the timer over before the timer could update and so never got these new deaths and time?)

Will record and log a run the next key I do and try and map the discrepancy, understand you're busy at the moment so this isn't a priority.

**Comment by ry-java** [comment]
Issue could potentially be related to WORLD_STATE_TIMER_START event not firing when deaths occur in keys passed the timer expiration

**Comment by Stinth** [comment]
Thanks for looking into this, pushing new version to curseforge.
