### ISSUE TITLE
Objective Tracker messed up

### ISSUE THREAD

**Issue by dnnyvst** [Stinth/GottaGoFaster#3]
Whenever I enable the addon, every time I reload (not even in a dungeon) my objective tracker frame is messed up.

![image](https://github.com/user-attachments/assets/a54940ab-daf3-4d5b-a31e-4d9d61e03da2)

**Comment by DNNYVST** [comment]
![image](https://github.com/user-attachments/assets/152df78c-1e3c-4cea-bfe0-482203fdb1c5)

**Comment by dnnyvst** [comment]
edit: remove lua errors, traced those to different addon

**Comment by dnnyvst** [comment]
I feel like it's not moving, it's actually just changing the Objective Tracker to be the height of the entire screen? If i move it at all in edit mode, it instantly snaps back to the "normal" height of the frame within edit mode.

**Comment by Stinth** [comment]
@DNNYVST Hello, thank you for the report. I will fix this issue before the launch of The War Within.

**Comment by Stinth** [comment]
Fixed in [v1.4.10](https://github.com/Stinth/GottaGoFaster/releases/tag/v1.4.10). Thanks again for the report.

**Comment by dnnyvst** [comment]
sweet!
