### ISSUE TITLE
/GGF command errors out 

### ISSUE THREAD

**Issue by cheeseslicer** [Stinth/GottaGoFaster#4]
When typing /ggf it throws a .lua error in the core.lua file.

The correction is as follws which opens up GGF options menu directly which starts at line 210:

function GottaGoFaster:ChatCommand(input)
  if (string.lower(input) == "debugmode") then
    GottaGoFaster.SetDebugMode(nil, (not GottaGoFaster.GetDebugMode(nil)));
  elseif (string.lower(input) == "changelog") then
    GottaGoFaster.Changelog();
  else
    local category = Settings.GetCategory("GottaGoFaster"); -- Replace with your actual category name
    if category then
      Settings.OpenToCategory("GottaGoFaster");
    else
      print("Category not found.");
    end
  end
end

**Comment by Stinth** [comment]
Thanks @cheeseslicer for the report and the PR.
Issue fixed with #5 and released [v1.4.8](https://github.com/Stinth/GottaGoFaster/releases/tag/v1.4.8)
