### ISSUE TITLE
LUA error in Utility.lua v1.4.10

### ISSUE THREAD

**Issue by dblanch369** [Stinth/GottaGoFaster#7]
Got this error after installing the latest version....

56x GottaGoFaster/Timer/Utility.lua:131: attempt to index global 'self' (a nil value)
[string "@GottaGoFaster/Timer/Utility.lua"]:131: in function `ShowObjectiveTracker'
[string "@GottaGoFaster/Core.lua"]:271: in function `ResetState'
[string "@GottaGoFaster/Core.lua"]:281: in function `WhereAmI'
[string "@GottaGoFaster/Core.lua"]:86: in function `?'
[string "@Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Ace3/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:
(*temporary) = UIParent {
 Tabs = <table> {
 }
 PixelSnapDisabled = true
 firstTimeLoaded = 1
 variablesLoaded = true
}
(*temporary) = nil
(*temporary) = UIParent {
 Tabs = <table> {
 }
 PixelSnapDisabled = true
 firstTimeLoaded = 1
 variablesLoaded = true
}
(*temporary) = "attempt to index global 'self' (a nil value)"

**Comment by Stinth** [comment]
Thank you for the report. This is fixed in [v1.4.11](https://github.com/Stinth/GottaGoFaster/releases/tag/v1.4.11)
