### ISSUE TITLE
Challengers Peril 15 Sec death penalty Timer fix

### ISSUE THREAD

**Issue by TheDescender** [Stinth/GottaGoFaster#8]
Can you please update so it takes the M+ affix Challengers Peril into account and updates the timer accordingly? Currently the timer is just completely off if you die once on anything higher than a 6. Thanks

**Comment by carlos93** [comment]
Fixed with https://github.com/Stinth/GottaGoFaster/pull/9

**Comment by Stinth** [comment]
Thank you for the PR, I'm very busy with RWF during these times.

**Comment by ry-java** [comment]
Fix appears to only do the text where it states the time lost. Made a PR for the timer too #10

**Comment by TheDescender** [comment]
> Fix appears to only do the text where it states the time lost. Made a PR for the timer too #10

Did #10 get merged into master and pushed to curseforge? Cause I just updated and still had massive discrepancy on timer in Grim Batol.

**Comment by Stinth** [comment]
v1.4.14 has been packaged as a new release, but curseforge seems to be slow at approving the new version.

**Comment by TheDescender** [comment]
Aight, guess i'll see after reset. EU, so no use in bothering with manually copying the repo I guess with current maintenance.
